### ISSUE TITLE
Tabs component

### ISSUE THREAD

**Issue by LewWadoo** [ant-design-rescript/components#5]
I am having difficulty converting the _AntD Tabs_ component to ReScript. How challenging is it, and why wasn't it implemented in your components?

**Comment by limitLiu** [comment]
> I am having difficulty converting the _AntD Tabs_ component to ReScript. How challenging is it, and why wasn't it implemented in your components?

Sorry, I haven't used Tabs in our company's projects, so I overlooked it. Another reason is that our company's project using ReScript has come to an end, so I haven't had much energy to keep up with AntD's changes recently. It's late at night for me now; I'll check on the issue when I have time during the day.

**Comment by LewWadoo** [comment]
Thank you for your answer! You don't need to address the issue, and feel
free to close it.

**Comment by LewWadoo** [comment]
I have successfully resolved my issue!
